---
title: "IBM 6500 Week 7 notes"
author: "Sandy Zhu"
format:
  html:
    toc: true
    number-sections: true
execute:
  echo: false
  warning: false
---

## Class announcement

Fall semester: Week 9 will be the first presentation ch2, ch3. Week15 will be the 2nd presentation Ch2,3. Week 13 finish data collection. Finish IRB first application.

In the same time, Fall semester IBM 6500 also have the personal assignments sush as SEM, Big Quiary

Spring semester: Week 6 first presentation (Ch4,initial data analysis), Week 9(data analysis with recommendation), week 15(create digital plan mock up content: email, graphic, video) IBM 6800, IBM6400

## Week 7 Topics and Assignment

1.  Github publication

    Can use positron or RStudio. Make sure to add html to the document to publish on github. Step by step.

2.  Survey

    How to convey client to do survey. If survey is required to do. Depend on your project if that will benefit client or do client want to do survey. Client data validation, secondary data. Primary data collection. Look into if the data are validate. Survey would be important because we have control over the quality and clearity of the data.

## Presentation Feedback

1.  This group uses C&M table is the blueprint for the survey. Company research, fresh company with a lot of new. users. to know how useful sales force is based on sales force records. Type of scale they used are strongly agree to strongly disagree. Defined by role, region, device, pilot group, user segment for nominal. Frequency, experience range, age group for the ordinal. To survey wheather salesforce improves job performance.

## Appendex

<https://github.com/qianzhucpp/IBM-6500-Individual-Project>
